
public enum OpcoesDoJogo {
	JOGAR, RANKING, INSTRUCOES, ZERAR_RANKING,
	AJUDA, CHUTAR_PALAVRA, CHUTAR_LETRA, PROXIMO_DESAFIO,
	LETRAS_SAIDAS, VOLTAR_PARA_MENU, TEMPO_ENCERRADO, 
	CADASTRAR_DESAFIO, REMOVER_DESAFIO, MOSTRAR_INSTRUCOES, SAIR
}